name: Generate gRPC Files

on:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23' # Укажите нужную версию Go

      - name: Install protoc
        run: |
          sudo apt-get install -y protobuf-compiler
          go get google.golang.org/protobuf/cmd/protoc-gen-go
          go get google.golang.org/grpc/cmd/protoc-gen-go-grpc
          go get github.com/envoyproxy/protoc-gen-validate

      - name: Generate gRPC and validate files
        run: |
          protoc-gen-validate --version
#      - name: Check generated files
#        run: |
#          git diff --exit-code generated/
